import { useEffect, useState } from 'react';
import client from '../../api/client';
import { PageHeader, Panel, LedgerTable, Select, Button } from '../../components/ui';

const DAYS = [['mon','Mon'],['tue','Tue'],['wed','Wed'],['thu','Thu'],['fri','Fri'],['sat','Sat']];

export default function TimetableManagement() {
    const [classes, setClasses] = useState([]); const [teachers, setTeachers] = useState([]); const [subjects, setSubjects] = useState([]); const [years, setYears] = useState([]); const [entries, setEntries] = useState([]); const [selectedClass, setSelectedClass] = useState(''); const [selectedSection, setSelectedSection] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
    const emptyForm = { school_class_id: '', section_id: '', subject_id: '', teacher_user_id: '', academic_year_id: '', day_of_week: 'mon', start_time: '', end_time: '' }; const [form, setForm] = useState(emptyForm);
    async function loadAll() { setLoading(true); try { const [c, t, s, y] = await Promise.all([client.get('/super-admin/school-classes').catch(() => ({ data: [] })), client.get('/admin/users', { params: { role: 'teacher' } }), client.get('/super-admin/subjects').catch(() => ({ data: [] })), client.get('/super-admin/academic-years').catch(() => ({ data: [] }))]); setClasses(c.data); setTeachers(t.data); setSubjects(s.data); setYears(y.data); } catch (err) { setError('Failed to load setup data.'); } finally { setLoading(false); } }
    useEffect(() => { loadAll(); }, []);
    async function loadEntries(classId, sectionId) { if (!classId || !sectionId) { setEntries([]); return; } const res = await client.get('/admin/timetable', { params: { school_class_id: classId, section_id: sectionId } }); setEntries(res.data); }
    const sectionsForClass = (id) => classes.find((c) => c.id === Number(id))?.sections ?? [];
    async function addEntry(e) { e.preventDefault(); try { await client.post('/admin/timetable', form); loadEntries(form.school_class_id, form.section_id); } catch (err) { setError(err.response?.data?.message || 'Failed to add period.'); } }
    async function deleteEntry(id) { if (!confirm('Remove this period?')) return; await client.delete(`/admin/timetable/${id}`); loadEntries(selectedClass, selectedSection); }
    if (loading) return <div className="p-8" style={{ color: '#6B7280' }}>Loading...</div>;
    return <><PageHeader title="Timetable" subtitle="Weekly schedule per class and section" /><div className="flex-1 overflow-y-auto p-4 sm:p-8 space-y-6">{error && <p className="text-sm" style={{ color: '#B3452D' }}>{error}</p>}<Panel title="Select class & section"><div className="flex gap-3 flex-wrap"><Select value={selectedClass} onChange={(e) => { setSelectedClass(e.target.value); setSelectedSection(''); setForm({ ...form, school_class_id: e.target.value, section_id: '' }); }} className="w-48"><option value="">Class...</option>{classes.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select value={selectedSection} onChange={(e) => { setSelectedSection(e.target.value); setForm({ ...form, section_id: e.target.value }); loadEntries(selectedClass, e.target.value); }} className="w-48" disabled={!selectedClass}><option value="">Section...</option>{sectionsForClass(selectedClass).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></div></Panel>{selectedSection && <Panel title="Weekly Periods"><LedgerTable columns={['Day', 'Time', 'Subject', 'Teacher', '']}>{entries.map((e) => <tr key={e.id} className="border-b last:border-0"><td className="py-2 pr-4 capitalize">{e.day_of_week}</td><td className="py-2 pr-4">{e.start_time} – {e.end_time}</td><td className="py-2 pr-4">{e.subject?.name}</td><td className="py-2 pr-4">{e.teacher?.name}</td><td><button onClick={() => deleteEntry(e.id)} className="text-xs" style={{ color: '#B3452D' }}>Remove</button></td></tr>)}{entries.length === 0 && <tr><td colSpan="5" className="py-6 text-center" style={{ color: '#6B7280' }}>No periods scheduled yet.</td></tr>}</LedgerTable><form onSubmit={addEntry} className="grid grid-cols-1 sm:grid-cols-3 gap-2 mt-4 pt-4 border-t"><Select value={form.day_of_week} onChange={(e) => setForm({ ...form, day_of_week: e.target.value })}>{DAYS.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</Select><input type="time" value={form.start_time} onChange={(e) => setForm({ ...form, start_time: e.target.value })} /><input type="time" value={form.end_time} onChange={(e) => setForm({ ...form, end_time: e.target.value })} /><Select value={form.subject_id} onChange={(e) => setForm({ ...form, subject_id: e.target.value })}><option value="">Subject...</option>{subjects.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select><Select value={form.teacher_user_id} onChange={(e) => setForm({ ...form, teacher_user_id: e.target.value })}><option value="">Teacher...</option>{teachers.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</Select><Select value={form.academic_year_id} onChange={(e) => setForm({ ...form, academic_year_id: e.target.value })}><option value="">Academic year...</option>{years.map((y) => <option key={y.id} value={y.id}>{y.name}</option>)}</Select><div className="sm:col-span-3"><Button type="submit">Add Period</Button></div></form></Panel>}</div></>;
}
